default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  encoding: utf8
  database: development
  username: root
  password: 

test: &test
  <<: *default
  database: test

production:
  <<: *default
  database: production